# Generated by Django 5.2.7 on 2025-10-25 14:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('clients', '0001_initial'),
        ('professionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Estrellas de 1 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, help_text='Comentario sobre la experiencia (opcional)', max_length=1000, verbose_name='Comentario')),
                ('professional_response', models.TextField(blank=True, max_length=500, verbose_name='Respuesta del profesional')),
                ('professional_response_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('is_approved', models.BooleanField(default=True, help_text='Reseña visible públicamente', verbose_name='Aprobada')),
                ('is_flagged', models.BooleanField(default=False, help_text='Marcada para revisión por contenido inapropiado', verbose_name='Marcada')),
                ('flagged_reason', models.TextField(blank=True, max_length=500, verbose_name='Razón de marcado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('booking', models.OneToOneField(help_text='Reserva asociada a esta reseña', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking', verbose_name='Reserva')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clients.client', verbose_name='Cliente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='professionals.professional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Contenido inapropiado'), ('offensive', 'Lenguaje ofensivo'), ('spam', 'Spam'), ('fake', 'Reseña falsa'), ('harassment', 'Acoso'), ('other', 'Otro')], max_length=20, verbose_name='Razón')),
                ('details', models.TextField(blank=True, max_length=500, verbose_name='Detalles')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('action_taken', 'Acción tomada'), ('dismissed', 'Desestimado')], default='pending', max_length=20, verbose_name='Estado')),
                ('resolution_notes', models.TextField(blank=True, max_length=500, verbose_name='Notas de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review', verbose_name='Reseña')),
            ],
            options={
                'verbose_name': 'Reporte de reseña',
                'verbose_name_plural': 'Reportes de reseñas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['professional', 'is_approved'], name='reviews_rev_profess_7b6bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', 'is_approved'], name='reviews_rev_rating_56f381_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='reviews_rev_created_03e07d_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['status', 'created_at'], name='reviews_rev_status_a3683e_idx'),
        ),
    ]
