# Generated by Django 5.2.7 on 2025-10-25 14:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID de reserva')),
                ('date', models.DateField(verbose_name='Fecha de la sesión')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('participants', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de participantes')),
                ('client_name', models.CharField(help_text='Nombre como aparece en la reserva', max_length=200, verbose_name='Nombre del cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email del cliente')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Teléfono del cliente')),
                ('is_first_time', models.BooleanField(default=False, verbose_name='Primera vez con el profesional')),
                ('client_notes', models.TextField(blank=True, help_text='Comentarios especiales, lesiones, objetivos, etc.', max_length=500, verbose_name='Notas del cliente')),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled_by_client', 'Cancelada por cliente'), ('cancelled_by_professional', 'Cancelada por profesional'), ('no_show', 'Cliente no asistió')], default='pending_payment', max_length=30, verbose_name='Estado')),
                ('cancellation_reason', models.TextField(blank=True, max_length=500, verbose_name='Razón de cancelación')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio al momento de la reserva', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Comisión de la plataforma (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de comisión')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de comisión')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado del pago')),
                ('reminder_sent_24h', models.BooleanField(default=False, verbose_name='Recordatorio 24hrs enviado')),
                ('reminder_sent_2h', models.BooleanField(default=False, verbose_name='Recordatorio 2hrs enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='clients.client', verbose_name='Cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=1000, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bookings.booking', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Nota de reserva',
                'verbose_name_plural': 'Notas de reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'date'], name='bookings_bo_client__df8c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service', 'date'], name='bookings_bo_service_f260d9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'date'], name='bookings_bo_status_c5c45f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'start_time'], name='bookings_bo_date_c2c738_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('service', 'date', 'start_time')},
        ),
    ]
